version: '3'
services:
  db:
    container_name: maker-bot-app-db
    image: postgres:15
    ports:
      - "5434:5432"
    restart: always
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: fff_db
      POSTGRES_USER: fff_user
      POSTGRES_PASSWORD: root
  web:
    container_name: maker-bot-app
    build: .
    restart: always
    ports:
      - "8096:8096"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fff_db
      SPRING_DATASOURCE_USERNAME: fff_user
      SPRING_DATASOURCE_PASSWORD: root